### PR TITLE
Plugin for Google Cloud Storage

### PR DESCRIPTION
**Pull request by noralife**
Hello. I would like to use cosbench for Google Cloud Storage.
I wrote a plugin for the storage as followed COSBenchAdaptorDevGuide.pdf.
Please kindly review my codes.

I already tested using Production Google Cloud Storage.
Here is a brief log:
|            ID             |    Name   |        Submitted-At           |              State     |
|------------------------|--------------|---------------------------------|-----------------------|
|  MA5DE0BCFD3  |      init     |   2015/12/01 14:09:48   |   accomplished  |
|  M25DE0F0EDD   |  prepare |   2015/12/01 14:10:01   |   accomplished  |
|  MF5DE1FBC38   |   main     |   2015/12/01 14:11:09   |   accomplished  |
|  M25DE2B4045    |  cleanup |   2015/12/01 14:11:57   |   accomplished  |
|  M15DE36EA30   |  dispose  |   2015/12/01 14:12:45   |   accomplished  |

### CODE REVIEW

**Comment by noralife** [comment]
@ywang19 
I could not understand the test report of Travis CI.
Could you explain what I should do for fixing?

**Comment by ywang19** [comment]
Hi Nanjo,

Thanks for your contributions! I will review the PR soon.


-yaguang

**Comment by ywang19** [comment]
yes, then refer the the file in sample-gcs-workload.xml, so others could know what the json file looks like, and how to get it.

other parts look fine to me, I will merge the PR when your sample json file is ready.

**Comment by noralife** [comment]
That's good idea. I put a sample json file in ./release/conf/ and change description in `sample-gcs-workload.xml` to urge to refer the file. Thank you for good advices.

**Pull request merged**
